"use client";

import { useRef } from "react";
import Link from "next/link";
import { useReveal } from "./useReveal";

const tile = "card p-8 md:p-10";

export default function MetricsStrip() {
  const ref = useRef<HTMLElement>(null);
  useReveal(ref);

  return (
    <section ref={ref} className="py-20 md:py-28">
      <div className="mx-auto w-full max-w-page px-5">
        <div data-item className="flex flex-col justify-between gap-3 md:flex-row md:items-end">
          <div>
            <p className="flex items-center gap-3 text-[12px] font-medium uppercase tracking-[0.2em] text-mute">
              <span className="h-px w-8 bg-ink/30" />
              01 — Highlights
            </p>
            <h2
              className="mt-4 font-medium leading-[1.05] tracking-[-0.03em] text-ink"
              style={{ fontSize: "clamp(34px, 5vw, 56px)" }}
            >
              Selected impact.
            </h2>
          </div>
          <Link href="/experience" className="text-[15px] text-ink underline decoration-ink/30 underline-offset-4 hover:decoration-ink">
            See all experience ›
          </Link>
        </div>

        <div className="mt-10 grid grid-cols-1 gap-4 md:grid-cols-6 md:gap-5">
          {/* headline stat */}
          <div data-item className={`${tile} md:col-span-4`}>
            <p className="text-[12px] font-medium uppercase tracking-[0.14em] text-mute">Octos Global Solutions</p>
            <p
              className="mt-4 font-light leading-none tracking-[-0.045em]"
              style={{ fontSize: "clamp(64px, 10vw, 120px)" }}
            >
              <span className="text-gradient">
                <span data-count="7000">7,000</span>+
              </span>
            </p>
            <p className="mt-5 max-w-md text-[19px] leading-[1.4] text-ink md:text-[21px]">
              leads a week, generated by an outreach pipeline I built from scratch — cutting
              manual work by 80%.
            </p>
          </div>

          <div data-item className={`${tile} md:col-span-2`}>
            <p className="text-[12px] font-medium uppercase tracking-[0.14em] text-mute">Churn model</p>
            <p className="mt-4 text-[52px] font-light leading-none tracking-[-0.04em] text-ink md:text-[60px]">
              $<span data-count="90">90</span>K
            </p>
            <p className="mt-4 text-[17px] leading-[1.45] text-mute">
              revenue protected by flagging at-risk accounts with 75% accuracy.
            </p>
          </div>

          <div data-item className={`${tile} md:col-span-2`}>
            <p className="text-[12px] font-medium uppercase tracking-[0.14em] text-mute">Data Decoders</p>
            <p className="mt-4 text-[52px] font-light leading-none tracking-[-0.04em] text-ink md:text-[60px]">
              <span data-count="200">200</span>+
            </p>
            <p className="mt-4 text-[17px] leading-[1.45] text-mute">
              students mentored in the analytics community I founded.
            </p>
          </div>

          <div data-item className={`${tile} md:col-span-2`}>
            <p className="text-[12px] font-medium uppercase tracking-[0.14em] text-mute">Research</p>
            <p className="mt-4 text-[52px] font-light leading-none tracking-[-0.04em] text-ink md:text-[60px]">
              <span data-count="3">3</span>
            </p>
            <p className="mt-4 text-[17px] leading-[1.45] text-mute">
              published papers on consumer analytics and data.{" "}
              <Link href="/publications" className="text-apple hover:underline">
                Read ›
              </Link>
            </p>
          </div>

          <div data-item className={`${tile} flex items-center gap-6 md:col-span-2`}>
            <img src="/lego.png" alt="Kush as a LEGO minifigure" className="h-28 w-auto" />
            <p className="text-[21px] font-semibold leading-[1.2] tracking-tight text-ink">
              Also available in <span className="text-gradient">LEGO.</span>
            </p>
          </div>

          {/* dark feature tile */}
          <div
            data-item
            className="relative overflow-hidden rounded-[20px] bg-ink p-8 text-white md:col-span-6 md:p-12"
          >
            <div aria-hidden className="glow glow-blue -right-20 -top-40 h-[380px] w-[520px] opacity-70" />
            <div className="relative flex flex-col justify-between gap-6 md:flex-row md:items-end">
              <div>
                <p className="text-[12px] font-medium uppercase tracking-[0.14em] text-white/50">Now</p>
                <p
                  className="mt-3 font-medium leading-[1.08] tracking-[-0.03em]"
                  style={{ fontSize: "clamp(30px, 4vw, 48px)" }}
                >
                  Marketing & Data Management Intern
                  <br />
                  <span className="text-white/55">at DaidaEx, New York.</span>
                </p>
              </div>
              <Link
                href="/experience"
                className="self-start whitespace-nowrap rounded-full bg-white px-6 py-3 text-[17px] text-ink transition-colors hover:bg-white/90 md:self-auto"
              >
                View timeline
              </Link>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
